name: Java and R CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin' # or 'zulu' or 'adopt' depending on your preference
        java-version: '11'

    - name: Build with Maven
      run: mvn clean install

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        install-r: true
        r-version: '4.1.0'  # or specify another version available without repository issues

    - name: Install R dependencies
      run: Rscript -e 'install.packages("ggplot2", repos="https://cloud.r-project.org")'

    - name: Run Java Application
      run: java -jar target/data-science-java-r-1.0-SNAPSHOT-jar-with-dependencies.jar
